/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IHM;

import Classes.User;
import Implements.UserService;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author anace
 */
public class Register_Inter extends javax.swing.JFrame {

     private static final String regex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";
	 private static final String regexT= "^[0-9]*$" ;
	  private static final String regexN= "^[a-zA-Z]*$" ;
	
     UserService us=new UserService();
    
    public Register_Inter() {
        initComponents();
        jLabel1.setText(null);
        Tn.setText("Nom ");
            Tn.setForeground(Color.gray);
            Tp.setText("Prenom ");
            Tp.setForeground(Color.gray);
         Te.setText("Email ");
          Tps.setEchoChar((char)0);
           Tpsc.setEchoChar((char)0);
            Te.setForeground(Color.gray);
           Tps.setText("Password ");
            Tps.setForeground(Color.gray);
            Tpsc.setText("Confirm Password ");
            Tpsc.setForeground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Te = new javax.swing.JTextField();
        Tps = new javax.swing.JPasswordField();
        Tpsc = new javax.swing.JPasswordField();
        showP = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        Tn = new javax.swing.JTextField();
        Tp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Te.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TeFocusLost(evt);
            }
        });
        Te.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeActionPerformed(evt);
            }
        });
        Te.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TeKeyReleased(evt);
            }
        });

        Tps.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TpsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TpsFocusLost(evt);
            }
        });
        Tps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TpsActionPerformed(evt);
            }
        });

        Tpsc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TpscFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TpscFocusLost(evt);
            }
        });
        Tpsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TpscKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TpscKeyTyped(evt);
            }
        });

        showP.setFont(new java.awt.Font("ITF Devanagari Marathi", 3, 12)); // NOI18N
        showP.setText("Show Password");
        showP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Tn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TnFocusLost(evt);
            }
        });
        Tn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TnKeyReleased(evt);
            }
        });

        Tp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TpFocusLost(evt);
            }
        });
        Tp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TpKeyReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/registre__3_-removebg-preview.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Hiragino Mincho ProN", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("...");

        jLabel2.setText("Nom : ");

        jLabel3.setText("Prneom :");

        jLabel5.setText("Email :");

        jLabel6.setText("Password :");

        jLabel7.setText("Confirm Password :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(showP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tpsc)
                            .addComponent(Tps)
                            .addComponent(Te)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Tn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tp, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Te, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tps, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tpsc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeActionPerformed

    private void TpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TpsActionPerformed

    private void TeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TeFocusLost
         if(Te.getText().equals("")){
            Te.setText("Email ");
            Te.setForeground(Color.gray);
        } 
    }//GEN-LAST:event_TeFocusLost

    private void TeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TeFocusGained
         if(Te.getText().equals("Email ")){
            Te.setText("");
            Te.setForeground(Color.black);
        }
    }//GEN-LAST:event_TeFocusGained

    private void TpsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpsFocusLost
         if(Tps.getText().equals("")){
             Tps.setEchoChar((char)0);
            Tps.setText("Password ");
            Tps.setForeground(Color.gray);
        } 
    }//GEN-LAST:event_TpsFocusLost

    private void TpsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpsFocusGained
         if(Tps.getText().equals("Password ")){
            Tps.setText("");
            Tps.setEchoChar('*');
            Tps.setForeground(Color.black);
        }    
    }//GEN-LAST:event_TpsFocusGained

    private void TpscFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpscFocusLost
        if(Tpsc.getText().equals("")){
            Tpsc.setEchoChar((char)0);
            Tpsc.setText("Confirm Password ");
            Tpsc.setForeground(Color.gray);
        }   
    }//GEN-LAST:event_TpscFocusLost

    private void TpscFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpscFocusGained
         if(Tpsc.getText().equals("Confirm Password ")){
            Tpsc.setText("");
            Tpsc.setEchoChar('*');
            Tpsc.setForeground(Color.black);
        
    }     
    }//GEN-LAST:event_TpscFocusGained

    private void TnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TnFocusLost
        if(Tn.getText().equals("")){
            Tn.setText("Nom ");
            Tn.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TnFocusLost

    private void TnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TnFocusGained
        if(Tn.getText().equals("Nom ")){
            Tn.setText("");
            Tn.setForeground(Color.black);
        }
    }//GEN-LAST:event_TnFocusGained

    private void TpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpFocusLost
         if(Tp.getText().equals("")){
            Tp.setText("Prenom ");
            Tp.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TpFocusLost

    private void TpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpFocusGained
         if(Tp.getText().equals("Prenom ")){
            Tp.setText("");
            Tp.setForeground(Color.black);
        }
    }//GEN-LAST:event_TpFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                String n=Tn.getText();
				String p=Tp.getText();
				String tm=Te.getText();
				String ps=Tps.getText();
				String psc=Tpsc.getText();
				/*
				if(no.equals("") && pr.equals("") && em.equals("") && ps.equals("") && psc.equals("")){
					JOptionPane.showMessageDialog(null, "les champs sont vides !");
				}else if(no.equals("")){
					JOptionPane.showMessageDialog(null, "nom vide !");
				}else if(pr.equals("")){
					JOptionPane.showMessageDialog(null, "prenom vide !");
				}else if(em.equals("")|| !emailvalide(Te.getText())){
					JOptionPane.showMessageDialog(null, "email vide !");
				}else if(ps.equals("")){
					JOptionPane.showMessageDialog(null, "pass vide !");
				}else if(psc.equals("") ){
					JOptionPane.showMessageDialog(null, "pass conf vide !");
				}
                                */
                                if(n.equals("") && p.equals("") && tm.equals("") && ps.equals("") && psc.equals("")){
					JOptionPane.showMessageDialog(null, "les champs sont vides !");
				}else
				if(n.equals("") || !NPvalide(n)){
					JOptionPane.showMessageDialog(null, "nom vide ou invalide !");
				}else if(p.equals("") || !NPvalide(p)){
					JOptionPane.showMessageDialog(null, "prenom vide ou invalide !");
				}else if(tm.equals("")|| !emailvalide(tm)){
					JOptionPane.showMessageDialog(null, "email vide ou invalide !");
				}else if(ps.equals("")){
                                    JOptionPane.showMessageDialog(null, "password vide !");
                                }else if(psc.equals("")){
                                    JOptionPane.showMessageDialog(null, "confirmer votre password !");
                                }else if(Tpsc.getText().equals(Tps.getText())){
                                    JOptionPane.showMessageDialog(null, "confirmer votre password != password!");
                                }else if(!us.register(new User(n,p,tm,ps))){
							Login_Inter lg=new Login_Inter();
							lg.setVisible(true);
							this.setVisible(false);
							Ref();
				}else {
					JOptionPane.showMessageDialog(null, "add user !!!");
					//Ref();
				}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPActionPerformed
        if(showP.isSelected()) {
		 			Tps.setEchoChar((char)0);
		 			Tpsc.setEchoChar((char)0);
		 		}else {
		 			Tps.setEchoChar('*');
		 			Tpsc.setEchoChar('*');
		 		}
    }//GEN-LAST:event_showPActionPerformed

    private void TpscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpscKeyTyped
        	
    }//GEN-LAST:event_TpscKeyTyped

    private void TpscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpscKeyReleased
        if(Tpsc.getText().equals(Tps.getText())) {
					Tps.setBorder(new LineBorder(Color.green,1));
					Tpsc.setBorder(new LineBorder(Color.green,1));
				//	mv.setText("mail invalide !!");
				}else {
					Tps.setBorder(new LineBorder(Color.red,1));
					Tpsc.setBorder(new LineBorder(Color.red,1));
					
				}
    }//GEN-LAST:event_TpscKeyReleased

    private void TeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeKeyReleased
        	if(!emailvalide(Te.getText())) {
					Te.setBorder(new LineBorder(Color.red,2));
					jLabel1.setText("mail invalide !!");
				}else {
					Te.setBorder(new LineBorder(Color.green,1));
					jLabel1.setText(null);
				}
    }//GEN-LAST:event_TeKeyReleased

    private void TnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TnKeyReleased
        if(!NPvalide(Tn.getText())) {
					Tn.setBorder(new LineBorder(Color.red,2));
				//	jLabel1.setText("mail invalide !!");
				}else {
					Tn.setBorder(new LineBorder(Color.green,1));
				//	jLabel1.setText(null);
				}
    }//GEN-LAST:event_TnKeyReleased

    private void TpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpKeyReleased
         if(!NPvalide(Tp.getText())) {
					Tp.setBorder(new LineBorder(Color.red,2));
				//	jLabel1.setText("mail invalide !!");
				}else {
					Tp.setBorder(new LineBorder(Color.green,1));
				//	jLabel1.setText(null);
				}
    }//GEN-LAST:event_TpKeyReleased

    public boolean emailvalide(String em) {
		Pattern p = Pattern.compile(regex);
		Matcher matcher = p.matcher(em);
		return matcher.matches();
	}
    
    public boolean Tellvalide(String tl) {
		Pattern p = Pattern.compile(regexT);
		Matcher matcher = p.matcher(tl);
		return matcher.matches();
	}
	public boolean NPvalide(String tl) {
		Pattern p = Pattern.compile(regexN);
		Matcher matcher = p.matcher(tl);
		return matcher.matches();
	}
	
	public void Ref() {
		Tn.setText(null);
		Tp.setText(null);
		Te.setText(null);
		Tps.setText(null);
		Tpsc.setText(null);
	}
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Inter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Te;
    private javax.swing.JTextField Tn;
    private javax.swing.JTextField Tp;
    private javax.swing.JPasswordField Tps;
    private javax.swing.JPasswordField Tpsc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox showP;
    // End of variables declaration//GEN-END:variables
}
